### ISSUE TITLE
Could not find a declaration file for module 'kompas'

### ISSUE THREAD

**Issue by psilvao** [pirxpilot/kompas#2]
Hello, I am starting to use your kompas module in my code, using vscode. I came across an observation that vscode tells me the following:

_**Could not find a declaration file for module 'kompas'
'/home/psilvao/brujula/node_modules/kompas/index.js' implicitly has an 'any' type.
   Try `npm install @ types / kompas` if it exists or add a new declaration (.d.ts) file containing` declare module 'kompas'; `ts (7016)**_

How can I solve this problem?

Thanks in advance
Pablo

**Comment by pirxpilot** [comment]
I am not using TypeScript (or vscode for that matter) myself, but there seem to be quite a few places you can find some info on how to add type definitions to any project. For example [this one][1]. Also check out [DefinitelyTyped][2]

[1]: https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/
[2]: https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package
